const { readFileSync, writeFileSync, mkdirSync } = require('fs');
const { resolve, join } = require('path');
const esbuild = require('esbuild');

const root = resolve(__dirname, '..');
const sources = [
  'segdefs.js',
  'transdefs.js',
  'nodenames.js',
  'wires.js',
  'expertWires.js',
  'chipsim.js',
  'memtable.js',
  'macros.js',
  'testprogram.js',
];
const banner = `/* Visual6502 expert simulator bundle. ` +
  `Generated by npm run build. */\n`;

(async function build() {
  const combined = sources
    .map((file) => readFileSync(join(root, file), 'utf8'))
    .join('\n\n');
  const result = await esbuild.transform(combined, {
    minify: true,
    target: 'es2017',
    legalComments: 'none',
  });
  const distPath = join(root, 'dist');
  mkdirSync(distPath, { recursive: true });
  writeFileSync(join(distPath, 'visual6502.js'), banner + result.code, 'utf8');
  console.log('Built visual6502.js for production');
})();

